name: "Test modules"

on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  deb:
    name: "Nginx-modules"
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: nginx/nginx
          path: ./nginx
          ref: master

      - name: Update apt
        run: sudo apt-get update

      - name: Install build-tool
        run: |
         sudo apt-get install -y \
         libssl-dev \
         lsb-release \
         libxml2-utils \
         xsltproc \
         devscripts \
         quilt \
         git \
         build-essential \
         ca-certificates \
         zlib1g-dev \
         libpcre3 \
         libpcre3-dev \
         tar \
         unzip \
         libssl-dev \
         libunwind-dev \
         pkg-config \
         make \
         gcc 
         
      - name: wget repo
        run: |
          cd nginx && \
          ./configure --add-module=../ && \
          make
